//! NAFEMS benchmark decks in `examples/nafems/`. Generated by
//! `solver/scripts/gen_nafems.py`. Targets from TNSB rev. 3 and the
//! Cameron / Casey / Simpson thermal plate.

#[cfg(test)]
mod tests {
    use crate::solve_native;

    fn load(name: &str) -> String {
        let p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../examples/nafems")
            .join(name);
        std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
    }

    fn node_of_set(inp: &str, set: &str) -> Vec<i32> {
        let model = crate::parse_model(inp).unwrap();
        model.expand_nset(set).unwrap()
    }

    /// LE1 elliptic membrane. σyy(D) target 92.7 MPa.
    #[test]
    fn nafems_le1_elliptic_membrane() {
        let inp = load("le1_cps8.inp");
        let out = solve_native(&inp).expect("LE1");
        let ids = node_of_set(&inp, "D");
        let ni = out.model.node_index(ids[0]).unwrap();
        let syy = out.stress[ni][1];
        let ux = out.u[ni][0];
        let target = 92.7;
        let err = (syy - target) / target;
        println!(
            "NAFEMS LE1  syy(D)={syy:.3} MPa  target={target}  err={:.2}%  ux={ux:.4} mm",
            err * 100.0
        );
        assert!(
            err.abs() < 0.02,
            "LE1 syy(D)={syy} MPa, target {target} (err {:.1}%)",
            err * 100.0
        );
        // Fino (fine quad9): ux(D) ≈ −0.102 mm. Hoop tension, radial displacement inward.
        assert!(
            (ux + 0.102).abs() < 0.01,
            "LE1 ux(D)={ux} mm, reference ≈ −0.102 mm"
        );
    }

    /// LE10 thick plate. σyy(D) target −5.38 MPa.
    #[test]
    fn nafems_le10_thick_plate() {
        let inp = load("le10_c3d20.inp");
        let out = solve_native(&inp).expect("LE10");
        let ids = node_of_set(&inp, "D");
        let ni = out.model.node_index(ids[0]).unwrap();
        let syy = out.stress[ni][1];
        let target = -5.38;
        let err = (syy - target) / target.abs();
        println!(
            "NAFEMS LE10 syy(D)={syy:.3} MPa  target={target}  err={:.2}%",
            err * 100.0
        );
        assert!(
            err.abs() < 0.05,
            "LE10 syy(D)={syy} MPa, target {target} (err {:.1}%)",
            err * 100.0
        );
    }

    /// Same plate, mesh refined past the NAFEMS 6×4×2 grid.
    #[test]
    fn nafems_le10_thick_plate_refined() {
        let inp = load("le10_c3d20_fine.inp");
        let out = solve_native(&inp).expect("LE10 fine");
        let ids = node_of_set(&inp, "D");
        let ni = out.model.node_index(ids[0]).unwrap();
        let syy = out.stress[ni][1];
        let target = -5.38;
        let err = (syy - target) / target.abs();
        println!(
            "NAFEMS LE10 fine syy(D)={syy:.3} MPa  target={target}  err={:.2}%",
            err * 100.0
        );
        assert!(
            err.abs() < 0.03,
            "LE10 fine syy(D)={syy} MPa, target {target} (err {:.1}%)",
            err * 100.0
        );
    }

    /// Thermal plate, T(0.6 m, 0.2 m) target 18.3 °C.
    #[test]
    fn nafems_t4_convection_plate() {
        let inp = load("t4_c3d8.inp");
        let out = solve_native(&inp).expect("T4");
        let ids = node_of_set(&inp, "PROBE");
        let mut tsum = 0.0;
        for id in &ids {
            let ni = out.model.node_index(*id).unwrap();
            // Heat solution stores temperature in u[0].
            tsum += out.u[ni][0];
        }
        let t = tsum / ids.len() as f64;
        let target = 18.3;
        println!(
            "NAFEMS T4   T(0.6,0.2)={t:.3} C  target={target}  err={:.2} C",
            t - target
        );
        assert!((t - target).abs() < 0.5, "T4 T={t} C, target {target}");
    }

    fn principals(s: &[f64; 6]) -> [f64; 3] {
        // In-plane principals plus σzz. Plate bending lives in xx/yy/xy.
        let mid = 0.5 * (s[0] + s[1]);
        let rad = (0.5 * (s[0] - s[1])).hypot(s[3]);
        let mut p = [mid + rad, mid - rad, s[2]];
        p.sort_by(|a, b| b.partial_cmp(a).unwrap());
        p
    }

    /// LE1 on quadratic triangles (CPS6).
    #[test]
    fn nafems_le1_cps6() {
        let inp = load("le1_cps6.inp");
        let out = solve_native(&inp).expect("LE1 CPS6");
        let ids = node_of_set(&inp, "D");
        let ni = out.model.node_index(ids[0]).unwrap();
        let syy = out.stress[ni][1];
        let target = 92.7;
        let err = (syy - target) / target;
        println!(
            "NAFEMS LE1 CPS6 syy(D)={syy:.3} MPa  target={target}  err={:.2}%",
            err * 100.0
        );
        assert!(
            err.abs() < 0.06,
            "LE1 CPS6 syy(D)={syy} (err {:.1}%)",
            err * 100.0
        );
    }

    /// LE6 skew plate, S8. Lower-surface principal stress 0.802 MPa.
    /// The shell recovery stores the z=+t/2 fibre; pure bending flips the sign
    /// on the opposite face, so the tensile principal is −σ_min.
    #[test]
    fn nafems_le6_skew_plate() {
        let inp = load("le6_s8.inp");
        let out = solve_native(&inp).expect("LE6");
        let ids = node_of_set(&inp, "E");
        let ni = out.model.node_index(ids[0]).unwrap();
        let s = out.stress[ni];
        let p = principals(&s);
        let tensile = p[0].max(-p[2]).max(-p[1]);
        let target = 0.802e6;
        let err = (tensile - target) / target;
        let uz = out.u[ni][2];
        println!(
            "NAFEMS LE6  σ1={:.4} MPa (fibre principals {:.3}/{:.3}/{:.3} MPa)  target=0.802  err={:.2}%  uz={uz:.6} m",
            tensile / 1e6,
            p[0] / 1e6,
            p[1] / 1e6,
            p[2] / 1e6,
            err * 100.0
        );
        assert!(
            err.abs() < 0.08,
            "LE6 σ1={:.4} MPa (err {:.1}%)",
            tensile / 1e6,
            err * 100.0
        );
    }
}
